# docker compose version which is currently 3.8
version: "3.8"

services:
  mymongodb:
    image: "mongo"

    ports:
      - "27017:27017"

    volumes:
      - data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: "anas"
      MONGO_INITDB_ROOT_PASSWORD: "12345"

  backend:
    build: ./backend
    ports:
      - "8080:8080"

    depends_on:
      - mymongodb

  frontend:
    build: ./task_management_client

    ports:
      - "3000:3000"
    volumes:
      - ./task_management_client/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - backend

# declare the volumes name that our app is using.
volumes:
  data:
