steps:
  - label: ":docker: Build"
    command: ./ops/bin/build.sh

  - wait

  - label: ":battery: Publish Image"
    command: ./ops/bin/pushImage.sh

  - wait

  - label: ":rocket: Deploy"
    command: ./ops/bin/deploy.sh
